### ISSUE TITLE
register-ml-on-click-id undefined

### ISSUE THREAD

**Issue by trev-dev** [Junker/stumpwm-pamixer#1]
Apologies, I am new to CL in general.

I packaged your contribution as a gnu guix package from source code. When I `asdf:load-system :pamixer` to try to use it, I get: undefined function: STUMPWM::REGISTER-ML-ON-CLICK-ID.

Any ideas for how to deal with this?

Edit: The error also occurs if I follow the README directions.

**Comment by Junker** [comment]
seems you are using old StumpWM version. This functionality was recently added:
https://github.com/stumpwm/stumpwm/blob/master/stumpwm.texi.in#L2095

you can update your StumpWM, or clone this repo with commit 1bc7c16aa0b102b9ec4db2f75f6a41344e3b4949

**Comment by Junker** [comment]
i just updated the code, it will work in any version, but for old versions the mouse click functionality will be disabled.

**Comment by trev-dev** [comment]
Thanks! Out of curiosity, what version is required? I'm currently running 1.0.1 - Aug 3 2022. I am fairly sure this is some mistake I'm making.

**Comment by Junker** [comment]
I'm using a git version from [AUR](https://aur.archlinux.org/packages/stumpwm-git). Don't know what version it was added exactly.

**Comment by trev-dev** [comment]
Fair enough.

Dmitry Kosenkov ***@***.***> writes:

> I'm using a git version from [AUR](https://aur.archlinux.org/packages/stumpwm-git). Don't know what version it was added exactly.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/Junker/stumpwm-pamixer/issues/1#issuecomment-1230069855
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

-- 

Trev : 0FB7 D06B 4A2A F07E AD5B  1169 183B 6306 8AA1 D206

**Comment by trev-dev** [comment]
Ok so I made a package using your latest commit and it works. Thanks for your help!

https://git.sr.ht/~trevdev/guix-channel/tree/main/item/trevdev/packages/stumpwm.scm#L13
